[package]
name = "lab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint-dig = { version = "0.8.2", features = ["prime"] }
num-integer = "0.1.45"
num-traits = "0.2.15"
rand = "0.8.5"
